### PR TITLE
Added a videoplayer controllable by ZOCP

### PR DESCRIPTION
**Pull request by sphaero**
Still in development so don't merge yet, still needs polishing

### CODE REVIEW

**Comment by sphaero** [comment]
K, canvas keystoning is not implemented but I reckon it can be merged?
Just don't play full-HD videos, it seems the GPU can't handle that with shaders

**Comment by fieldOfView** [comment]
The implementation does not respond to signals, only to values set using SET (urwid, nodeeditor). See my use of on_modified, on_peer_signalled and receive_value for an approach to respond to both:
https://github.com/fieldOfView/pyZUtilities/blob/master/zswitchin.py#L73
An overrideable "receive_value" method could be a useful helper to add to ZOCP.

**Comment by sphaero** [comment]
yeah, it's still a bit unclear how this should be handled. I created an issue for it: https://github.com/z25/pyZOCP/issues/69
I think it is also happening though emit_signal. At least I think I tested it.
https://github.com/sphaero/ZOCPApps/blob/zvideo/zvideo/zvideoplayer.py#L223

**Comment by fieldOfView** [comment]
I'll shoot you a pull-request tomorrow

**Pull request merged**
